services:
  be:
    build: .
    container_name: backend-container
    command: bash startup.sh
    ports:
      - "127.0.0.1:8000:10000" # TODO: For development only!
    environment:
      - TAXI_DB_URL=${DB_LANG}+${DB_DRIVER}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${TAXI_HOST}:${POSTGRES_PORT}/${TAXI_DB}
      - HOUSING_DB_URL=${DB_LANG}+${DB_DRIVER}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HOUSING_HOST}:${POSTGRES_PORT}/${HOUSING_DB}
      - DOTENV_PATH=${DOTENV_PATH}
    volumes:
      - .:/code:cached # TODO: For development only!
    depends_on:
      taxi-db:
        condition: service_healthy
      housing-db:
        condition: service_healthy
  taxi-db:
    image: postgis/postgis:16-3.4-alpine
    container_name: ${TAXI_HOST}
    restart: always
    expose:
      - "${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${TAXI_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${TAXI_DB}", "-U", "${POSTGRES_USER}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 50s
  housing-db:
    image: postgis/postgis:16-3.4-alpine
    container_name: ${HOUSING_HOST}
    restart: always
    expose:
      - "${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${HOUSING_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${HOUSING_DB}", "-U", "${POSTGRES_USER}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 50s
